minVersion: 1.2.0
changelog: CHANGELOG.md
changelogPolicy: auto
preReleaseCommand: bash scripts/bump-version.sh
github:
  owner: getsentry
  repo: sentry-nodestore-s3
artifactProvider:
  name: github
targets:
  - name: github
  - name: pypi
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi